# Generated by Django 2.2.2 on 2021-03-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=17)),
                ('user_address', models.TextField(blank=True, default='')),
                ('user_city', models.CharField(blank=True, default='', max_length=50)),
                ('user_state', models.CharField(blank=True, default='', max_length=50)),
                ('user_country', models.CharField(blank=True, default='', max_length=50)),
                ('user_pincode', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
